# Generated by Django 3.1.2 on 2020-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employecreation',
            name='designation',
            field=models.CharField(default='Engineer', max_length=100, verbose_name='Designation'),
            preserve_default=False,
        ),
    ]
