# Generated by Django 3.1.2 on 2020-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employecreation_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employecreation',
            name='phone',
            field=models.IntegerField(max_length=10, verbose_name='Phone'),
        ),
    ]
