# Generated by Django 3.1.4 on 2020-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20201129_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employecreation',
            name='designation',
            field=models.CharField(choices=[('SOFTWARE ENGINEER', 'Software Engineer'), ('TEST ENGINEER', 'Test Engineer'), ('DEVELOPER', 'Devoleper'), ('BUSSINESS ANALYST', 'Bussiness Analyst'), ('AI ENGINEER', 'AI Engineer'), ('DEVOOPS ENGINEER', 'Devops Engineer')], max_length=100, verbose_name='Designation'),
        ),
    ]
